Server:
  RunMode: debug
  # RunMode: release
  HttpPort: 8888
  ReadTimeout: 60
  WriteTimeout: 60
App:
  LogSavePath: storage/logs
  LogFileName: app
  LogFileExt: .log
  # 根据level定义不同字母出现概率，区分为不同难度
  Level:
    1: [20, 3, 3, 1]
    2: [20, 2, 2, 1]
    3: [20, 1, 1, 1]
    # 补位权重，此处固定
    999: [1, 1, 1, 1]
Database:
  DBType: mysql
  Username: root
  Password: 123456
  Host: localhost:3306
  DBName: jelly
  TablePrefix: jelly_
  Charset: utf8
  ParseTime: True
  MaxIdleConns: 10
  MaxOpenConns: 30
